### ISSUE TITLE
Using with Docker

### ISSUE THREAD

**Issue by jeremehancock** [rg9400/Trakt-Arr-Integration#2]
Thanks for the scripts. Really saved the day for me.

I am running Sonarr and Radarr using Docker. I had too edit the scripts to remove "v3" from the URLs. I am running the latest v3 for both. Once I made those changes things worked great. 

Just figured you would want to know.

**Comment by rg9400** [comment]
That's strange, I also use Docker and have no issues with the v3 in the URL...that should use the latest version of the API. Removing it will use the older v2 API which I guess works with these scripts, but it's strange why the newer one fails for you

**Comment by jeremehancock** [comment]
You know I had a few other issues before I tried that change. I didn't have Trakt setup as a connection in Radarr and I need to update python. So maybe the v3 wasn't really an issue. I will check and let you know. 

These scripts are great. I had one movie missing in my Trakt collection for some reason and this saved me so much time.

**Comment by jeremehancock** [comment]
Well disregard. :) I just checked and everything works great as is. The only thing that I really had an issue with is not having Trakt setup in Radarr as a connection.

Thanks again for these scripts!!
