### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by CelticWebSolutions** [rg9400/Trakt-Arr-Integration#4]
Is this script still working?  I attempted to us etch radarr collection sync and it won't work for me, I change dates radarr url but its' still giving this error

`File "/volume3/docker/trakt-Sync/Trakt-Arr-Integration-master/radarr_collection_sync.py", line 32, in <module>
    trakt_notification = next(notification for notification in radarr_notifications if notification['implementation'] == "Trakt")
StopIteration`

Am I missing something obvious here?

Thanks in advance for your help :)

**Comment by rg9400** [comment]
I haven't checked in a while because of the native Radarr implementation, but I just ran it right now and it worked.

Make sure you have a Trakt connection set up that has been authenticated already in Radarr

**Comment by CelticWebSolutions** [comment]
Was totally my fault, once I read through etc code I realised that it was using the trait integration in Radarr to push the data. I didn't have the radarr one setup because I'd always used Plex integration and didn't even realise radarr and sonarr had integration built in.

Thanks of the prompt response, all is working now and my back catalogue has been added.
